python:
  - 3.5
notifications: # set notification options
  slack:
    rooms:
      - ucsc-cgl:Edwfgt7MJEVZV9Lib3igueTF
    on_success: change
    on_failure: always
  email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install autotools-dev autoconf cmake curl libbz2-dev zlib1g-dev liblzma-dev libeigen3-dev libhdf5-dev
  - sudo apt-get update

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - pwd
#  Install boost
  - cd $HOME/build/adbailey4/
  - wget -O boost_1_69_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.69.0/boost_1_69_0.tar.gz/download
  - tar xzf boost_1_69_0.tar.gz >/dev/null
  - cd boost_1_69_0/
  - ./bootstrap.sh --show-libraries
  - ./bootstrap.sh --with-libraries=system,date_time,filesystem,iostreams,coroutine2 >/dev/null #--prefix=/usr/
  - echo something
  - sudo ./b2 install
  #  Install htslib
  - cd $HOME/build/adbailey4/
  - wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2
  - tar -vxjf htslib-1.9.tar.bz2
  - ls
  - cd htslib-1.9
  - ./configure
  - make
  - sudo make install
#  - echo "PATH=$HOME/build/adbailey4/bin/:$PATH" >> ~/.bashrc
#  - source ~/.bashrc
  - cd /home/travis/build/adbailey4/embed_fast5
  - python setup.py install
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ../
  - make


script:
  - make check
