sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=travisbot
    - secure: GXeg6z5eepBQoPYhav6zybXK6i8Ptn19tTKElBirvShW6i9hzhTUJ8H0nmXBziCHnGyGSQCVBUkL3CK7mlrkbBu2qCj+Fe6rXxnqjhrEtfK0SMntXXiV9EcvGiyf8Q/+YG/i0WN5BE8IYkJ+SuHtW0G7PFyg69XEbvleCJaQthK7aj0YvtCeooBozIhVTCIdUJZxWhVIUJNpfWy2BdYmWksqUrmef8NwnJhPNDeQWOqajK15anB2nuytscN54GQFlOAkXfaIvBbSr5+7oStwFJ6Kpcspc6ZlrDZZpp/kM3Q7rRmsff3992NFKtyzOWPQqGghnFqI/R9R2xVdOtFkmLtfdHKQBIISrvE+cDiDbs2VKfsUX5RXflPQoVKu2Wv4Ne97ErK6KiP8w2woiXbFNBHiFocMlE2Vz7NxVvIT6rqutEaj+SFrv0O1QbeLBLd1G7oZQVrwooEJlQtfPwpw/cWO/4rZfQprhSmjTb2+c5EYcr48es2gGl/TEjz8urIGVh/81DL6QxJVK2ypwh04oPCtMFiLQvsDbKQFwm0ZYDGn2AcMvJCJtRHlD1KnW63zUULb+yfJTqx25hSQ6NxM6LP8MrzbTBjJUzJd1Z/xfVi+XWxiYNQNQmDc7CZjVsSSRgo3vzCbbpcVji9gNssfwKphbcRaOT9cMCCGGC9iLfA=
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}

notifications:
  slack:
    secure: izQuWHVK+LWJKH9T8m/8iQHeONpwdW3qA1qFqImgYuCLKlpiS/69t9fuTPZ8E+YYGqRq6aZ/yr5wF/Cau3nx0fEGDiZJPcWk++pp6g9mpsua+8egKxsSV2RbGokCUHF7xs15/PCbh84QLXPJVyDSpisqtSF9HvxJ8FV+U8AIOAM3XYmRRaSPhe8e4HP6HCPTtJQdD8W8Cj3LEo+kugY4En0iY+zNFPoiYiJhADhJIfzymDUJbAuo4uWtc1GBn+UHVz26orzymDSDiGSAyVzQRgrbZznts516ZQ7to1uQ45qfqJEJhtkoL//FzEcCqd79juCkHAVQt9jvsq9LTaRDbGxyfLFaiBPaKDL9oErTlHbpyPMSOIpR8CPvo/E/bBUeZjsMHbE8tdz5WOpAiTE2VpziS66RDt6KHsPNWxxBrUsF8s92TV3FMI7FhiwzbIzGxaHr/APZmUJf6588SxGdLO7ek/yJL1IWoxh7TCjdfRZMzw9oWxykqvlUIBI3eHn6E0IAHH2q70Vuq8y4zJvrr3JpEYj+mWdoN19uNAjZqJr+xwwi0cO7MAhr+SnaxMP29wwuymCRyXBVuz/1EcKpHEh3w3rAnnVQ6xhvEjST7LmQ8pp9WjCrfglRGMQMQUnpGqxxxb9fRlfAz/GzgDAjlEhQWNX05vwO0f5PNcKuG4w=
  email: false
language: generic

jobs:
  include:
    - os: linux
      dist: bionic


before_install:
#  docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - docker --version
  - docker pull ucscbailey/embed || true
script:
  - cp Docker/Dockerfile .
  - docker build --progress=plain --pull --cache-from ucscbailey/embed --tag ucscbailey/embed .
  - docker run ucscbailey/embed

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push ucscbailey/embed
  on:
    branch: travis_docker_integration

