python:
  - 3.5
notifications: # set notification options
  slack:
    rooms:
      - ucsc-cgl:Edwfgt7MJEVZV9Lib3igueTF
    on_success: change
    on_failure: always
  email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-dev libbz2-dev zlib1g-dev autotools-dev autoconf cmake
  - sudo apt-get install libboost-all-dev libeigen3-dev curl liblzma-dev
  -
install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - pwd
  - cd /usr/include
  - ls
  - cd /home/travis/build/adbailey4/
  - git clone --recursive https://github.com/jts/nanopolish.git
  - cd nanopolish
  - make HDF5=noinstall
  - cd ..
  - cd embed_fast5
  - mkdir build
  - cd build
  - cmake -DNANOPOLISH_HOME:STRING=../nanopolish ../
  - make


script:
  - make check
