python:
  - 3.5
notifications: # set notification options
  slack:
    rooms:
      - ucsc-cgl:Edwfgt7MJEVZV9Lib3igueTF
    on_success: change
    on_failure: always
  email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-dev libbz2-dev zlib1g-dev autotools-dev autoconf cmake
  - sudo apt-get install libboost-all-dev libeigen3-dev curl liblzma-dev
  - sudo apt-get update


install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - pwd
  - python setup.py install
  - mkdir cmake-build
  - cd cmake-build
  - cmake ../
  - make


script:
  - make check
