//
// Created by Andrew Bailey on 5/23/20.
//

#ifndef EMBED_FAST5_TESTS_SRC_BINARYEVENTTESTS_HPP_
#define EMBED_FAST5_TESTS_SRC_BINARYEVENTTESTS_HPP_

#endif //EMBED_FAST5_TESTS_SRC_BINARYEVENTTESTS_HPP_
