//
// Created by Andrew Bailey on 5/3/20.
//

#ifndef EMBED_FAST5_TESTS_SRC_PERPOSITIONKMERSTESTS_HPP_
#define EMBED_FAST5_TESTS_SRC_PERPOSITIONKMERSTESTS_HPP_

#endif //EMBED_FAST5_TESTS_SRC_PERPOSITIONKMERSTESTS_HPP_
